openapi: 3.1.0
info:
  title: Default Sleuth API
  description: API Specification for the Default Sleuth project
  version: 1.0.0

servers:
  - url: https://tleqd94bfd.execute-api.us-east-1.amazonaws.com/dev
    description: Dev API


security:
  - cognitoAuth: [email, openid]

paths:
  /dashboard:
    get:
      summary: Dashboard data
      security:
        - cognitoAuth: []
      responses:
        '200':
          description: Returns dashboard data
          content:
            application/json:
              schema:
                $ref: './schemas/dashboard/dashboard.schema.json'
        '401':
          description: Unauthorized

  /loan_queue:
    get:
      summary: Loan queue data
      security:
        - cognitoAuth: []
      responses:
        '200':
          description: Returns loan queue data
          content:
            application/json:
              schema:
                $ref: './schemas/work_queue/loanQueue.schema.json'
        '401':
          description: Unauthorized

  /user/{id}:
    get:
      summary: Get user by ID
      security:
        - cognitoAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: The user ID
          schema:
            type: string
      responses:
        '200':
          description: User info
          content:
            application/json:
              schema:
                $ref: './schemas/user/user.schema.json'
        '401':
          description: Unauthorized
        '404':
          description: User not found

components:
  securitySchemes:
    cognitoAuth:
      type: oauth2
      x-tokenName: id_token
      flows:
        authorizationCode:
          authorizationUrl: https://us-east-1mlmm6zjt7.auth.us-east-1.amazoncognito.com/oauth2/authorize
          tokenUrl: https://us-east-1mlmm6zjt7.auth.us-east-1.amazoncognito.com/oauth2/token
          scopes:
            email: "Access to the user's email"
            openid: "Grants access to the openid scope"
