openapi: 3.1.0
info:
  title: Default Sleuth API
  description: API Specification for the Default Sleuth project
  version: 1.0.0

servers:
  - url: https://tleqd94bfd.execute-api.us-east-1.amazonaws.com/dev/v2
    description: Dev API


security:
  - cognitoAuth: [email, openid]

paths:
  /dashboard:
    get:
      summary: Dashboard data
      description: |
        This endpoint provides all data needed for Dashboard page.

        # Frontend components
        ## Total Loan Portfolio, Total Balance at Risk, and Total Balance Saved
        Data for the these components (at the top of the dashboard) come from `data["loan_metrics_summary"]`. 

        ### Mappings:
        
        - **Total Loan Portfolio** -> `data["loan_metrics_summary"]["balance_total"]`
          - **Dollar amount** -> `data["loan_metrics_summary"]["balance_total"]["amount"]`
          - **Percent change** -> `data["loan_metrics_summary"]["balance_total"]["percent_change"]`

        - **Total Balance at Risk** -> `data["loan_metrics_summary"]["balance_at_risk"]`
          - **Dollar amount** -> `data["loan_metrics_summary"]["balance_at_risk"]["amount"]`
          - **Percent change** -> `data["loan_metrics_summary"]["balance_at_risk"]["percent_change"]`

        - **Total Balance Saved** -> `data["loan_metrics_summary"]["balance_saved"]`
          - **Dollar amount** -> `data["loan_metrics_summary"]["balance_saved"]["amount"]`
          - **Percent change** -> `data["loan_metrics_summary"]["balance_saved"]["percent_change"]`

        ## Balances by Core Status
        
        Data for this component (below top level metrics, left) come from `data["core_status_summary"]`. This is an array of objects, where each object has the following properties:

        - `"label"`: Corresponds to e.g. "Current", "30-60 DPD", etc. in the current UI.
        - `"count"`: Corresponds to the number in parentheses and the "Count" field in the tooltip.
        - `"amount"`: Corresponds to the "Balance" field in the tooltip and determines the size of sectors. 

        ## Charge Off Rate: Actual vs Expected
        
        Data for this (right of **Balances by Core Status**) come from `data["charge_off_rates_monthly"]`. This is a **sorted** array of objects, where each object has the following properties:

        - `"month"`: Determines the x-axis label
        - `"actual"`: Determines the y-axis value for the "actual" line
        - `"expected"`: Determines the y-axis value for the "expected" line

        ## Healthy, Watchlist, and Intervention
        
        Data for these metric components (top component under "Portfolio" tab) come from `data["default_category_balances"]`. 

        ### Mappings:

        - **Healthy** -> `data["default_category_balances"]["healthy"]`
        - **Watchlist** -> `data["default_category_balances"]["watchlist"]`
        - **Intervention** -> `data["default_category_balances"]["intervention"]`

        ## Default Risk Tiers

        Data for this component (below the above metrics, formatted as table) come from `data["loan_balance_matrix"]`. This is a **sorted** array of objects (each corresponding to a cell in the table), where each object has the following properties:

        - `"balance"`: The dollar amount (or null, if none) to put in the cell
        - `"value_tier"`: Corresponds to the row labels, e.g. "$300k+", "$100k", etc. in the current UI.
        - `"risk_tier"`: Corresponds to the column labels, e.g. "25", "50", etc. in the current UI.
        - `"value_tier_order"` and `"risk_tier_order"`: Order for rows/columns; as the data is sorted, likely not needed. 

        The data is sorted first by `"value_tier"` and then by `"risk_tier"`; in other words, the array is an array of cells that should be populated into the grid left to right, top to bottom. 


      security:
        - cognitoAuth: []
      responses:
        '200':
          description: Returns dashboard data
          content:
            application/json:
              schema:
                $ref: './schemas/v2/dashboard/responses/get_dashboard.schema.json'
        '401':
          description: Unauthorized
  /users:
    get:
      summary: Get users
      security:
        - cognitoAuth: []
      responses:
        '200':
          description: All organization users
          content:
            application/json:
              schema:
                $ref: './schemas/v2/users/responses/get_users.schema.json'
        '401':
          description: Unauthorized
    post:
      summary: Create user
      security:
        - cognitoAuth: []
      requestBody:
        description: For testing purposes, please end the user email with **@default-sleuth.test.com** to prevent excess Cognito emails from being sent.
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/v2/users/requests/post_user.schema.json'
            example:
              name: Test Admin
              role_id: 1
              email: testuser@default-sleuth.test.com
      responses:
        '200':
          description: User info
          content:
            application/json:
              schema:
                $ref: './schemas/v2/users/responses/post_user.schema.json'
        '401':
          description: Unauthorized
  /users/{user_id}:
    delete:
      summary: Delete user
      security:
        - cognitoAuth: []
      parameters:
        - name: user_id
          in: path
          required: true
          description: ID of the user to delete
          schema:
            type: string
      responses:
        '200':
          description: User deletion confirmation
          content:
            application/json:
              schema:
                $ref: './schemas/v2/users/responses/delete_user.schema.json'
        '401':
          description: Unauthorized
  /members/{member_id}:
    get:
      summary: Get member by ID
      security:
        - cognitoAuth: []
      parameters:
        - name: member_id
          in: path
          required: true
          description: The member (internal) ID
          schema:
            type: string
      responses:
        '200':
          description: Member info
          content:
            application/json:
              schema:
                $ref: './schemas/v2/members/responses/get_member.schema.json'
        '401':
          description: Unauthorized
  /loans:
    get:
      summary: Get loan queue data
      security:
        - cognitoAuth: []
      responses:
        '200':
          description: Returns loan queue data
          content:
            application/json:
              schema:
                $ref: './schemas/v2/loans/responses/get_loans.schema.json'
        '401':
          description: Unauthorized
  /loans/{account_id}:
    patch:
      summary: Modify loan ds_status/promise_date/modification_date
      security:
        - cognitoAuth: []
      parameters:
        - name: account_id
          in: path
          required: true
          description: The loan (internal) ID
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/v2/loans/requests/patch_loan.schema.json'
            example:
              ds_status: in_progress
              modification_date: 2025-03-01
      responses:
        '200':
          description: Updated loan data
          content: 
            application/json:
              schema:
                $ref: './schemas/v2/loans/responses/patch_loan.schema.json'
  /loans/{account_id}/contact_history:
    post:
      summary: Create contact history entry
      security:
        - cognitoAuth: []
      parameters:
        - name: account_id
          in: path
          required: true
          description: The loan (internal) ID
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './schemas/v2/contact_history/requests/post_contact_history.schema.json'
            example:
              date: 2025-03-20
              contact_type: Phone Call
              notes: Test entry, sorry about the dups
              status: Completed
              agent: Swagger Agent
      responses:
        '200':
          description: 'Contact history entry'
          content:
            application/json:
              schema:
                $ref: './schemas/v2/contact_history/responses/post_contact_history.schema.json'
        '401':
          description: Unauthorized

components:
  securitySchemes:
    cognitoAuth:
      type: oauth2
      x-tokenName: id_token
      flows:
        authorizationCode:
          authorizationUrl: https://us-east-1mlmm6zjt7.auth.us-east-1.amazoncognito.com/oauth2/authorize
          tokenUrl: https://us-east-1mlmm6zjt7.auth.us-east-1.amazoncognito.com/oauth2/token
          scopes:
            email: "Access to the user's email"
            openid: "Grants access to the openid scope"
